### PR TITLE
Update transformers for auto-gptq support, drop CUDA deps when unused

### PR DESCRIPTION
**Pull request by charles-dyfis-net**

### CODE REVIEW

**Comment by charles-dyfis-net** [comment]
Before removing from draft:

- [ ] Smoketest the various playground targets on Linux
- [ ] Smoketest the various playground targets on Mac
- [ ] Test for regressions on MacOS
- [ ] Test whether libc code is needed on MacOS; make a noop otherwise

**Comment by charles-dyfis-net** [comment]
On further testing, this hits a bug already fixed in #198. Probably saner to fold the llama.cpp version bump into here so there's only one PR to merge.

**Comment by charles-dyfis-net** [comment]
- [ ] Address regression on Linux: `torch.cuda.is_available()` is `False` even in the `-all` configuration.

**Comment by charles-dyfis-net** [comment]
Apologies about the amount of time this was sitting in draft; I quite forgot that it wasn't finished earlier.

**Comment by lbeurerkellner** [comment]
Awesome, thanks.

**Pull request merged**
