### PR TITLE
Merged docker image project and added documentation.

### PR DESCRIPTION
**Pull request by SilacciA**
After speaking to Luca, I merged my project of docker image and added the Dockerfile into scripts and also modified the documentation by adding the docker-setup to the Contribute section of the documentation.

### CODE REVIEW

**Comment by lbeurerkellner** [comment]
Thanks, this looks great. I just tested locally. For images with GPU enabled, there is an issue with the `accelerate` package missing.

I checked the Dockerfile, and instead of manually installing the torch dependency, we could simply install LMQL via `pip install lmql[hf]`, which will also include the missing `accelerate` package automatically. Could you please extend this?

Otherwise, happy to merge :) Thanks a lot.

**Comment by SilacciA** [comment]
I will make the changes, thanks for pointing that out !

**Comment by SilacciA** [comment]
Changes are done through the last commit [16de1f3](https://github.com/eth-sri/lmql/pull/70/commits/16de1f349f0936618a93276883207545f126758a)

**Comment by lbeurerkellner** [comment]
Great, thank you for your contribution :) Merging now.

**Pull request merged**
