### PR TITLE
Enable running playground on windows

### PR DESCRIPTION
**Pull request by mosheduminer**
This launches the playground successfully, but when I try to run the "this is a test" query, the results never show up. And strangely, I'm not asked for an openai key either (using the openai model in the query and settings). Do you have any ideas?

### CODE REVIEW

**Comment by mosheduminer** [comment]
This PR is meant to fix #4.

**Comment by lbeurerkellner** [comment]
I think I found the issue. There are at least two things that still need to be changed:

* In this file, we assume unix linebreaks `\n`, but we also need to support Windows `\r` line breaks: https://github.com/eth-sri/lmql/blob/faff95d5035072309f1e97e581c7a340a27ad15d/src/lmql/ui/live/live.js#L40
* One of the search paths for an `api.env` file that contains the OpenAI secret here (https://github.com/eth-sri/lmql/blob/faff95d5035072309f1e97e581c7a340a27ad15d/src/lmql/runtime/openai_secret.py#L27), does not exist on Windows. We should exclude it if HOME returns None. An even better solution would be to provide a Windows-specific additional search path.

More generally, we also would need a way to set OPENAI_SECRET or the Azure equivalents from a cmd.exe or PowerShell. I am not very familiar with this, but there should be ways to read out environment variables from inside a Python process there, right?

**Comment by mosheduminer** [comment]
I fixed the first issue (line endings), but now I get the error that
```
 "OpenAI models are not compatible with HuggingFace tokenizers. Please use 'tiktoken' or 'gpt3_tokenizer' instead."
AssertionError: OpenAI models are not compatible with HuggingFace tokenizers. Please use 'tiktoken' or 'gpt3_tokenizer' instead.
App finished running with exit code 1
```

In CMD, variables are set with `SET OPENAI_API_KEY=sk-...` by the way.

**Comment by lbeurerkellner** [comment]
Sorry, for the delay. Now, I could finally test it on my windows machine. It all seems to work with your current state.

The issue your seem to be encountering is likely unrelated and may be caused by not having `tiktoken` installed? Can you try installing `tiktoken` and run again? We use `gpt2` for all OpenAI models, since Chat models do not support tokenized input anyway and text-* models are all based on the GPT-2 vocabulary.

**Comment by mosheduminer** [comment]
Thanks. I'm traveling right now and don't have my windows laptop. But I don't think I installed any extra dependencies, so it's likely that.

**Comment by lbeurerkellner** [comment]
Great, merging this for now then, and please report back if you still encounter issues with the tokenizer. Thanks a lot for your contribution.

**Comment by mosheduminer** [comment]
Sounds good, thanks.

**Pull request merged**
